version: '3.1'

services:
  factorial-app:
    build: .
    depends_on:
      - factorial-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://factorial-db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  factorial-db:
    image: postgres:14-alpine
    expose:
       - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123