version: '3.1'

services:
  factorial-app:
    build: .
    depends_on:
      - factorial-db
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://factorial-db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081


  factorial-db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
      #expose:
      # - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123